apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: health-v1
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: health-v1
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
